import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  PutCommand,
  UpdateCommand,
  GetCommand,
} from '@aws-sdk/lib-dynamodb';
import * as crypto from 'crypto';

const ddbClient = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(ddbClient);

// Table names are generated by Amplify - these will be set via environment variables
const CONVERSATION_TABLE = process.env.CONVERSATION_TABLE_NAME || 'Conversation';
const MESSAGE_TABLE = process.env.MESSAGE_TABLE_NAME || 'Message';
const TOOLCALL_TABLE = process.env.TOOLCALL_TABLE_NAME || 'ToolCall';
const ORG_STATS_TABLE = process.env.ORG_STATS_TABLE_NAME || 'OrgStats';

interface ToolCallPayload {
  toolName: string;
  durationMs?: number;
  status?: 'ok' | 'error';
  metadata?: Record<string, unknown>;
}

interface IngestPayload {
  orgId: string;
  sessionId: string;
  conversationId?: string;
  messageId: string;
  receivedAt: string;
  respondedAt: string;
  userText: string;
  assistantText: string;
  status: 'ok' | 'error';
  latencyMs?: number;
  toolCalls?: ToolCallPayload[];
  escalated?: boolean;
  tokensIn?: number;
  tokensOut?: number;
}

interface LambdaEvent {
  headers: Record<string, string>;
  body: string;
  isBase64Encoded?: boolean;
}

interface LambdaResponse {
  statusCode: number;
  headers: Record<string, string>;
  body: string;
}

function verifyHmacSignature(body: string, signature: string | undefined): boolean {
  const secret = process.env.INGEST_SECRET;
  
  if (!secret || !signature) {
    console.error('Missing secret or signature');
    return false;
  }

  const expectedSignature = crypto
    .createHmac('sha256', secret)
    .update(body)
    .digest('hex');

  // Use timingSafeEqual to prevent timing attacks
  try {
    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expectedSignature)
    );
  } catch {
    return false;
  }
}

function generateId(): string {
  return crypto.randomUUID();
}

function truncateText(text: string, maxLength: number = 100): string {
  if (!text) return '';
  return text.length > maxLength ? text.substring(0, maxLength) + '...' : text;
}

async function upsertConversation(
  orgId: string,
  conversationId: string,
  sessionId: string,
  userText: string,
  assistantText: string,
  status: 'ok' | 'error',
  escalated: boolean,
  timestamp: string
): Promise<void> {
  try {
    // Try to get existing conversation
    const existing = await docClient.send(
      new GetCommand({
        TableName: CONVERSATION_TABLE,
        Key: { id: conversationId },
      })
    );

    if (existing.Item) {
      // Update existing conversation
      await docClient.send(
        new UpdateCommand({
          TableName: CONVERSATION_TABLE,
          Key: { id: conversationId },
          UpdateExpression: `
            SET lastMessageAt = :lastMessageAt,
                messageCount = messageCount + :increment,
                lastUserMessagePreview = :userPreview,
                lastAssistantMessagePreview = :assistantPreview,
                #status = :status,
                escalationCount = escalationCount + :escalationIncrement,
                updatedAt = :updatedAt
          `,
          ExpressionAttributeNames: {
            '#status': 'status',
          },
          ExpressionAttributeValues: {
            ':lastMessageAt': timestamp,
            ':increment': 2, // user + assistant messages
            ':userPreview': truncateText(userText),
            ':assistantPreview': truncateText(assistantText),
            ':status': status,
            ':escalationIncrement': escalated ? 1 : 0,
            ':updatedAt': timestamp,
          },
        })
      );
    } else {
      // Create new conversation
      await docClient.send(
        new PutCommand({
          TableName: CONVERSATION_TABLE,
          Item: {
            id: conversationId,
            orgId,
            sessionId,
            createdAt: timestamp,
            lastMessageAt: timestamp,
            messageCount: 2,
            lastUserMessagePreview: truncateText(userText),
            lastAssistantMessagePreview: truncateText(assistantText),
            status,
            escalationCount: escalated ? 1 : 0,
            updatedAt: timestamp,
          },
        })
      );
    }
  } catch (error) {
    console.error('Error upserting conversation:', error);
    throw error;
  }
}

async function insertMessages(
  orgId: string,
  conversationId: string,
  sessionId: string,
  messageId: string,
  userText: string,
  assistantText: string,
  receivedAt: string,
  respondedAt: string,
  latencyMs: number | undefined,
  toolUsed: boolean,
  escalated: boolean,
  tokensIn?: number,
  tokensOut?: number
): Promise<string> {
  const userMessageId = `${messageId}-user`;
  const assistantMessageId = messageId;

  // Insert user message
  await docClient.send(
    new PutCommand({
      TableName: MESSAGE_TABLE,
      Item: {
        id: userMessageId,
        orgId,
        conversationId,
        sessionId,
        createdAt: receivedAt,
        role: 'user',
        text: userText,
        toolUsed: false,
        escalated: false,
      },
    })
  );

  // Insert assistant message
  await docClient.send(
    new PutCommand({
      TableName: MESSAGE_TABLE,
      Item: {
        id: assistantMessageId,
        orgId,
        conversationId,
        sessionId,
        createdAt: respondedAt,
        role: 'assistant',
        text: assistantText,
        latencyMs,
        tokensIn,
        tokensOut,
        toolUsed,
        escalated,
      },
    })
  );

  return assistantMessageId;
}

async function insertToolCalls(
  orgId: string,
  messageId: string,
  toolCalls: ToolCallPayload[],
  timestamp: string
): Promise<void> {
  for (const toolCall of toolCalls) {
    await docClient.send(
      new PutCommand({
        TableName: TOOLCALL_TABLE,
        Item: {
          id: generateId(),
          orgId,
          messageId,
          toolName: toolCall.toolName,
          startedAt: timestamp,
          endedAt: timestamp,
          durationMs: toolCall.durationMs || 0,
          status: toolCall.status || 'ok',
          metadata: toolCall.metadata || {},
        },
      })
    );
  }
}

async function updateOrgStats(
  orgId: string,
  status: 'ok' | 'error',
  escalated: boolean,
  latencyMs: number | undefined
): Promise<void> {
  const now = new Date();
  const period = now.toISOString().substring(0, 10); // YYYY-MM-DD

  try {
    await docClient.send(
      new UpdateCommand({
        TableName: ORG_STATS_TABLE,
        Key: { orgId, period },
        UpdateExpression: `
          SET totalConversations = if_not_exists(totalConversations, :zero) + :convIncrement,
              totalMessages = if_not_exists(totalMessages, :zero) + :msgIncrement,
              totalUserMessages = if_not_exists(totalUserMessages, :zero) + :one,
              totalAssistantMessages = if_not_exists(totalAssistantMessages, :zero) + :one,
              totalEscalations = if_not_exists(totalEscalations, :zero) + :escalationIncrement,
              totalErrors = if_not_exists(totalErrors, :zero) + :errorIncrement,
              updatedAt = :updatedAt
        `,
        ExpressionAttributeValues: {
          ':zero': 0,
          ':one': 1,
          ':convIncrement': 0, // We don't increment here, handled in upsert
          ':msgIncrement': 2,
          ':escalationIncrement': escalated ? 1 : 0,
          ':errorIncrement': status === 'error' ? 1 : 0,
          ':updatedAt': now.toISOString(),
        },
      })
    );
  } catch (error) {
    console.error('Error updating org stats:', error);
    // Don't throw - stats update failure shouldn't fail the ingestion
  }
}

export const handler = async (event: LambdaEvent): Promise<LambdaResponse> => {
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type, X-Signature',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Content-Type': 'application/json',
  };

  // Handle CORS preflight
  if (event.headers['x-forwarded-method'] === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: corsHeaders,
      body: '',
    };
  }

  try {
    // Get the raw body
    const rawBody = event.isBase64Encoded
      ? Buffer.from(event.body, 'base64').toString('utf-8')
      : event.body;

    // Verify HMAC signature
    const signature = event.headers['x-signature'] || event.headers['X-Signature'];
    
    if (!verifyHmacSignature(rawBody, signature)) {
      console.error('Invalid HMAC signature');
      return {
        statusCode: 401,
        headers: corsHeaders,
        body: JSON.stringify({ error: 'Invalid signature' }),
      };
    }

    // Parse the payload
    const payload: IngestPayload = JSON.parse(rawBody);

    // Validate required fields
    if (!payload.orgId || !payload.sessionId || !payload.messageId) {
      return {
        statusCode: 400,
        headers: corsHeaders,
        body: JSON.stringify({ error: 'Missing required fields: orgId, sessionId, messageId' }),
      };
    }

    if (!payload.userText || !payload.assistantText) {
      return {
        statusCode: 400,
        headers: corsHeaders,
        body: JSON.stringify({ error: 'Missing required fields: userText, assistantText' }),
      };
    }

    // Use sessionId as conversationId if not provided
    const conversationId = payload.conversationId || payload.sessionId;
    const timestamp = payload.respondedAt || new Date().toISOString();
    const toolUsed = (payload.toolCalls && payload.toolCalls.length > 0) || false;

    // Upsert conversation
    await upsertConversation(
      payload.orgId,
      conversationId,
      payload.sessionId,
      payload.userText,
      payload.assistantText,
      payload.status,
      payload.escalated || false,
      timestamp
    );

    // Insert messages
    const assistantMessageId = await insertMessages(
      payload.orgId,
      conversationId,
      payload.sessionId,
      payload.messageId,
      payload.userText,
      payload.assistantText,
      payload.receivedAt || timestamp,
      timestamp,
      payload.latencyMs,
      toolUsed,
      payload.escalated || false,
      payload.tokensIn,
      payload.tokensOut
    );

    // Insert tool calls if present
    if (payload.toolCalls && payload.toolCalls.length > 0) {
      await insertToolCalls(
        payload.orgId,
        assistantMessageId,
        payload.toolCalls,
        timestamp
      );
    }

    // Update org stats
    await updateOrgStats(
      payload.orgId,
      payload.status,
      payload.escalated || false,
      payload.latencyMs
    );

    return {
      statusCode: 200,
      headers: corsHeaders,
      body: JSON.stringify({
        success: true,
        conversationId,
        messageId: assistantMessageId,
      }),
    };
  } catch (error) {
    console.error('Ingestion error:', error);
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({ error: 'Internal server error' }),
    };
  }
};

